Document: todo.txt-cli
Title: Debian todo.txt-cli Manual
Author: <insert document author here>
Abstract: This manual describes what todo.txt-cli is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/todo.txt-cli/todo.txt-cli.sgml.gz

Format: postscript
Files: /usr/share/doc/todo.txt-cli/todo.txt-cli.ps.gz

Format: text
Files: /usr/share/doc/todo.txt-cli/todo.txt-cli.text.gz

Format: HTML
Index: /usr/share/doc/todo.txt-cli/html/index.html
Files: /usr/share/doc/todo.txt-cli/html/*.html
